### PR TITLE
Fix canonical-order of RData

### LINKED ISSUE #113: Verification failure for 1.in-addr.arpa. NS
```
 % dug --demo -i 1.in-addr.arpa. NS +dnssec
...
fill delegation - verification success - RRSIG of DS: "." -> "arpa."
...
delegationWithCache: "arpa." -> "in-addr.arpa.", delegation - verification success - RRSIG of DS
...
delegationWithCache: "in-addr.arpa." -> "1.in-addr.arpa.", delegation - verification success - RRSIG of DS
...
resolve-just: query ("1.in-addr.arpa.",NS) selected addresses: 200.3.13.14
query "1.in-addr.arpa." NS to 200.3.13.14#53/UDP
verification failed - RRSIG of "1.in-addr.arpa." NS
;; 1sec 370usec

;; HEADER SECTION:
;Standard query, ServFail, id: 0
;Flags: Recursion Desired, Recursion Available


;; QUESTION SECTION:
;1.in-addr.arpa.		IN	NS
...
```

### PR DESCRIPTION
**Pull request by khibino**
When sorting RRs in canonical order in RRset, the octet sequence should have been sorted excluding the length of RData.

Here is a test case to reproduce this issue
https://github.com/kazu-yamamoto/dnsext/commit/1120bcb01dc7a733d7a7cc17fe15881ac55062aa

This should fix #113 .

### CODE REVIEW

**Comment by kazu-yamamoto** [comment]
Could you add a comment to refer the specification?

**Comment by khibino** [comment]
> Could you add a comment to refer the specification?

add note about sort-order https://github.com/kazu-yamamoto/dnsext/pull/129/commits/3e1076560613a78da14f2083bafce022e2d928ff

File: dnsext-dnssec/DNS/SEC/Verify/Verify.hs [hunk 1]
```diff
@@ -126,10 +126,12 @@ verifyRRSIGwith RRSIGImpl{..} now dnskey@RD_DNSKEY{..} rrsig@RD_RRSIG{..} rrset_
 
 {- Canonical RR Ordering within an RRset
    https://datatracker.ietf.org/doc/html/rfc4034#section-6.3
-   Assumes same ( rrname, rrtype, rrclass, rrttl ).
-   Same order between RData and RR, under same ( rrname, rrtype, rrclass, rrttl ). -}
+   "RRs with the same owner name,
```
Comment (kazu-yamamoto) [inline dnsext-dnssec/DNS/SEC/Verify/Verify.hs:129]: Would you add "RFC 4034 Section 6.3:"

Comment (khibino) [reply dnsext-dnssec/DNS/SEC/Verify/Verify.hs:129]: https://github.com/kazu-yamamoto/dnsext/pull/129/commits/edb8a00258d42aa0aca94e82f52fb02ee1fa793a

**Review by kazu-yamamoto — APPROVED** [review]
LGTM
